# Generated by Django 4.2.13 on 2026-09-14 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("colleges", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IDCardSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "border_color",
                    models.CharField(
                        default="#000000", help_text="Hex color code", max_length=7
                    ),
                ),
                ("top_background", models.CharField(default="#FFFFFF", max_length=7)),
                ("card_school_name", models.CharField(max_length=255)),
                ("school_name_font_size", models.IntegerField(default=14)),
                (
                    "school_name_color",
                    models.CharField(default="#000000", max_length=7),
                ),
                ("school_address", models.CharField(blank=True, max_length=500)),
                (
                    "school_address_color",
                    models.CharField(default="#000000", max_length=7),
                ),
                ("id_no_font_size", models.IntegerField(default=12)),
                ("id_no_color", models.CharField(default="#000000", max_length=7)),
                ("id_no_background", models.CharField(default="#FFFFFF", max_length=7)),
                ("title_font_size", models.IntegerField(default=12)),
                ("title_color", models.CharField(default="#000000", max_length=7)),
                ("value_font_size", models.IntegerField(default=11)),
                ("value_color", models.CharField(default="#000000", max_length=7)),
                ("bottom_signature", models.CharField(max_length=255)),
                (
                    "signature_background",
                    models.CharField(default="#FFFFFF", max_length=7),
                ),
                ("signature_color", models.CharField(default="#000000", max_length=7)),
                (
                    "signature_align",
                    models.CharField(
                        choices=[
                            ("left", "Left"),
                            ("center", "Center"),
                            ("right", "Right"),
                        ],
                        default="center",
                        max_length=10,
                    ),
                ),
                (
                    "card_logo",
                    models.ImageField(
                        blank=True,
                        help_text="Max: 100x110px",
                        null=True,
                        upload_to="card_logos/",
                    ),
                ),
                (
                    "college",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="colleges.college",
                    ),
                ),
            ],
            options={
                "db_table": "id_card_settings",
            },
        ),
        migrations.CreateModel(
            name="AdmitCardSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("border_color", models.CharField(default="#000000", max_length=7)),
                ("top_background", models.CharField(default="#FFFFFF", max_length=7)),
                ("card_school_name", models.CharField(max_length=255)),
                ("school_name_font_size", models.IntegerField(default=14)),
                (
                    "school_name_color",
                    models.CharField(default="#000000", max_length=7),
                ),
                ("school_address", models.CharField(blank=True, max_length=500)),
                (
                    "school_address_color",
                    models.CharField(default="#000000", max_length=7),
                ),
                ("admit_title_font_size", models.IntegerField(default=16)),
                (
                    "admit_title_color",
                    models.CharField(default="#000000", max_length=7),
                ),
                (
                    "admit_title_background",
                    models.CharField(default="#FFFFFF", max_length=7),
                ),
                ("title_font_size", models.IntegerField(default=12)),
                ("title_color", models.CharField(default="#000000", max_length=7)),
                ("value_font_size", models.IntegerField(default=11)),
                ("value_color", models.CharField(default="#000000", max_length=7)),
                ("exam_title_font_size", models.IntegerField(default=13)),
                ("exam_title_color", models.CharField(default="#000000", max_length=7)),
                ("subject_font_size", models.IntegerField(default=11)),
                ("subject_color", models.CharField(default="#000000", max_length=7)),
                ("bottom_signature", models.CharField(max_length=255)),
                (
                    "signature_background",
                    models.CharField(default="#FFFFFF", max_length=7),
                ),
                ("signature_color", models.CharField(default="#000000", max_length=7)),
                (
                    "signature_align",
                    models.CharField(
                        choices=[
                            ("left", "Left"),
                            ("center", "Center"),
                            ("right", "Right"),
                        ],
                        default="center",
                        max_length=10,
                    ),
                ),
                (
                    "card_logo",
                    models.ImageField(blank=True, null=True, upload_to="card_logos/"),
                ),
                (
                    "college",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="colleges.college",
                    ),
                ),
            ],
            options={
                "db_table": "admit_card_settings",
            },
        ),
    ]
