# Generated by Django 4.2.13 on 2026-09-14 23:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("colleges", "0002_initial"),
        ("teachers", "0001_initial"),
        ("hr", "0001_initial"),
        ("students", "0001_initial"),
        ("academic", "0002_initial"),
        ("templates", "0001_initial"),
        ("attendance", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="teacherattendance",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendances",
                to="teachers.teacher",
            ),
        ),
        migrations.AddField(
            model_name="studentattendance",
            name="college",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="colleges.college",
            ),
        ),
        migrations.AddField(
            model_name="studentattendance",
            name="marked_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="student_attendances_marked",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="studentattendance",
            name="school_class",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="academic.schoolclass"
            ),
        ),
        migrations.AddField(
            model_name="studentattendance",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="academic.classsection"
            ),
        ),
        migrations.AddField(
            model_name="studentattendance",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendances",
                to="students.student",
            ),
        ),
        migrations.AddField(
            model_name="employeeattendance",
            name="college",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="colleges.college",
            ),
        ),
        migrations.AddField(
            model_name="employeeattendance",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendances",
                to="hr.employee",
            ),
        ),
        migrations.AddField(
            model_name="employeeattendance",
            name="marked_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employee_attendances_marked",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="absentsmslog",
            name="college",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="colleges.college",
            ),
        ),
        migrations.AddField(
            model_name="absentsmslog",
            name="sent_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="absentsmslog",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="templates.smstemplate",
            ),
        ),
        migrations.AddField(
            model_name="absentemaillog",
            name="college",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="colleges.college",
            ),
        ),
        migrations.AddField(
            model_name="absentemaillog",
            name="sent_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="absentemaillog",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="templates.emailtemplate",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="teacherattendance",
            unique_together={("teacher", "attendance_date")},
        ),
        migrations.AddIndex(
            model_name="studentattendance",
            index=models.Index(
                fields=["attendance_date", "school_class", "section"],
                name="student_att_attenda_7ed09a_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="studentattendance",
            unique_together={("student", "attendance_date")},
        ),
        migrations.AlterUniqueTogether(
            name="employeeattendance",
            unique_together={("employee", "attendance_date")},
        ),
    ]
