# Generated by Django 4.2.13 on 2025-11-28 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AcademicYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("year", models.CharField(help_text="e.g., 2023-2024", max_length=20)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "is_active",
                    models.BooleanField(
                        default=False, help_text="Currently running academic year"
                    ),
                ),
                (
                    "is_running",
                    models.BooleanField(
                        default=False, help_text="Is this the current running session"
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True, help_text="Additional notes or remarks"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Academic Years",
                "db_table": "admin_academic_years",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("export", "Export"),
                            ("import", "Import"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "module",
                    models.CharField(
                        help_text="e.g., 'Students', 'Finance'", max_length=100
                    ),
                ),
                ("action_description", models.TextField()),
                (
                    "object_id",
                    models.IntegerField(
                        blank=True, help_text="ID of the affected object", null=True
                    ),
                ),
                (
                    "object_name",
                    models.CharField(
                        blank=True,
                        help_text="Name/title of affected object",
                        max_length=255,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
            ],
            options={
                "verbose_name_plural": "Activity Logs",
                "db_table": "admin_activity_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EmailSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "email_protocol",
                    models.CharField(
                        choices=[
                            ("smtp", "SMTP"),
                            ("sendgrid", "SendGrid"),
                            ("mailgun", "Mailgun"),
                            ("aws_ses", "AWS SES"),
                        ],
                        default="smtp",
                        max_length=50,
                    ),
                ),
                (
                    "email_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("notification", "Notification"),
                            ("confirmation", "Confirmation"),
                            ("transactional", "Transactional"),
                            ("marketing", "Marketing"),
                        ],
                        max_length=50,
                    ),
                ),
                ("smtp_host", models.CharField(blank=True, max_length=255)),
                ("smtp_port", models.IntegerField(blank=True, null=True)),
                ("smtp_username", models.CharField(blank=True, max_length=255)),
                ("smtp_password", models.CharField(blank=True, max_length=500)),
                (
                    "smtp_security",
                    models.CharField(
                        blank=True,
                        choices=[("tls", "TLS"), ("ssl", "SSL"), ("none", "None")],
                        max_length=50,
                    ),
                ),
                (
                    "smtp_timeout",
                    models.IntegerField(
                        default=5, help_text="SMTP Timeout in seconds (5-10)"
                    ),
                ),
                ("from_email", models.EmailField(max_length=254)),
                ("from_name", models.CharField(max_length=255)),
                (
                    "charset",
                    models.CharField(
                        choices=[
                            ("UTF-8", "UTF-8"),
                            ("ISO-8859-1", "ISO-8859-1"),
                            ("ASCII", "ASCII"),
                            ("UTF-16", "UTF-16"),
                        ],
                        default="UTF-8",
                        max_length=50,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                        ],
                        default="normal",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("send_to_parents", models.BooleanField(default=False)),
                ("send_to_students", models.BooleanField(default=False)),
                ("send_to_staff", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name_plural": "Email Settings",
                "db_table": "admin_email_settings",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "feedback_type",
                    models.CharField(
                        choices=[
                            ("bug", "Bug Report"),
                            ("feature", "Feature Request"),
                            ("improvement", "Improvement Suggestion"),
                            ("complaint", "Complaint"),
                            ("praise", "Praise"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("resolved", "Resolved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("resolution_notes", models.TextField(blank=True)),
            ],
            options={
                "verbose_name_plural": "Feedback",
                "db_table": "admin_feedback",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "code",
                    models.CharField(
                        help_text="Language code (e.g., 'en', 'hi', 'ur'). No spaces, capitals, or special characters.",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Language display name (e.g., 'English', 'Hindi')",
                        max_length=100,
                    ),
                ),
                (
                    "base_language",
                    models.CharField(
                        default="en",
                        help_text="Base language for fallback translations",
                        max_length=20,
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Is this a predefined default language?",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Can this language be used?"
                    ),
                ),
                (
                    "is_custom",
                    models.BooleanField(
                        default=False, help_text="Was this language created by user?"
                    ),
                ),
                (
                    "rtl_support",
                    models.BooleanField(
                        default=False,
                        help_text="Enable Right-to-Left support for this language (e.g., Arabic, Urdu, Hebrew)",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Language description/notes"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Languages",
                "db_table": "admin_languages",
                "ordering": ["-is_default", "name"],
                "unique_together": {("code",)},
            },
        ),
        migrations.CreateModel(
            name="OpeningHour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "day",
                    models.CharField(
                        choices=[
                            ("monday", "Monday"),
                            ("tuesday", "Tuesday"),
                            ("wednesday", "Wednesday"),
                            ("thursday", "Thursday"),
                            ("friday", "Friday"),
                            ("saturday", "Saturday"),
                            ("sunday", "Sunday"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("opening_time", models.TimeField()),
                ("closing_time", models.TimeField()),
                ("is_holiday", models.BooleanField(default=False)),
                ("remarks", models.TextField(blank=True)),
            ],
            options={
                "verbose_name_plural": "Opening Hours",
                "db_table": "admin_opening_hours",
                "ordering": ["day"],
            },
        ),
        migrations.CreateModel(
            name="SchoolPaymentSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "payment_gateway",
                    models.CharField(
                        choices=[
                            ("stripe", "Stripe"),
                            ("paypal", "PayPal"),
                            ("razorpay", "Razorpay"),
                            ("bank_transfer", "Bank Transfer"),
                        ],
                        max_length=50,
                    ),
                ),
                ("gateway_api_key", models.CharField(max_length=500)),
                ("gateway_secret_key", models.CharField(max_length=500)),
                ("merchant_account", models.CharField(blank=True, max_length=255)),
                (
                    "payment_terms",
                    models.CharField(
                        choices=[
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("half_yearly", "Half Yearly"),
                            ("annual", "Annual"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "late_fee_percentage",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                (
                    "late_fee_days",
                    models.IntegerField(
                        default=5, help_text="Days after due date to apply late fee"
                    ),
                ),
                (
                    "discount_percentage",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "School Payment Settings",
                "db_table": "admin_school_payment_settings",
            },
        ),
        migrations.CreateModel(
            name="SMSSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("twilio", "Twilio"),
                            ("aws_sns", "AWS SNS"),
                            ("nexmo", "Nexmo"),
                            ("local", "Local Provider"),
                        ],
                        max_length=50,
                    ),
                ),
                ("api_key", models.CharField(max_length=500)),
                ("api_secret", models.CharField(blank=True, max_length=500)),
                ("sender_id", models.CharField(max_length=20)),
                ("is_active", models.BooleanField(default=False)),
                (
                    "send_to_parents",
                    models.BooleanField(default=False, help_text="Send SMS to parents"),
                ),
                (
                    "send_to_students",
                    models.BooleanField(
                        default=False, help_text="Send SMS to students"
                    ),
                ),
                (
                    "send_to_staff",
                    models.BooleanField(default=False, help_text="Send SMS to staff"),
                ),
                ("monthly_sms_limit", models.IntegerField(default=1000)),
                ("sms_sent_count", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "SMS Settings",
                "db_table": "admin_sms_settings",
            },
        ),
        migrations.CreateModel(
            name="LanguageLabel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "label_key",
                    models.CharField(
                        help_text="Unique identifier for label (e.g., 'btn_submit', 'msg_welcome', 'err_invalid_email')",
                        max_length=255,
                    ),
                ),
                (
                    "label_value",
                    models.TextField(help_text="Translated text for this label"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of what this label is used for",
                    ),
                ),
                (
                    "is_system",
                    models.BooleanField(
                        default=False,
                        help_text="Is this a system label? (Cannot be deleted)",
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        help_text="Language for this label",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="labels",
                        to="admin_settings.language",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Language Labels",
                "db_table": "admin_language_labels",
                "ordering": ["label_key"],
            },
        ),
        migrations.CreateModel(
            name="GeneralSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "brand_name",
                    models.CharField(
                        blank=True, help_text="Brand/Organization name", max_length=255
                    ),
                ),
                (
                    "brand_title",
                    models.CharField(
                        blank=True, help_text="Brand title (Required)", max_length=255
                    ),
                ),
                (
                    "brand_logo",
                    models.ImageField(
                        blank=True,
                        help_text="Logo dimensions: Max-W: 100px, Max-H: 110px",
                        null=True,
                        upload_to="brand/",
                    ),
                ),
                (
                    "favicon_icon",
                    models.ImageField(
                        blank=True,
                        help_text="Favicon dimensions: Max-W: 20px, Max-H: 20px",
                        null=True,
                        upload_to="brand/",
                    ),
                ),
                (
                    "brand_footer",
                    models.TextField(
                        blank=True, help_text="Footer text/copyright information"
                    ),
                ),
                ("school_name", models.CharField(blank=True, max_length=255)),
                (
                    "school_code",
                    models.CharField(blank=True, max_length=50, unique=True),
                ),
                ("school_address", models.TextField(blank=True)),
                ("school_phone", models.CharField(blank=True, max_length=20)),
                ("school_email", models.EmailField(blank=True, max_length=254)),
                ("school_website", models.URLField(blank=True)),
                (
                    "school_logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="school_settings/"
                    ),
                ),
                ("principal_name", models.CharField(blank=True, max_length=255)),
                ("principal_email", models.EmailField(blank=True, max_length=254)),
                (
                    "academic_year_start",
                    models.DateField(
                        blank=True, help_text="Start of academic year", null=True
                    ),
                ),
                (
                    "academic_year_end",
                    models.DateField(
                        blank=True, help_text="End of academic year", null=True
                    ),
                ),
                ("timezone", models.CharField(default="UTC", max_length=50)),
                ("currency", models.CharField(default="USD", max_length=10)),
                (
                    "currency_symbol",
                    models.CharField(
                        default="$",
                        help_text="Currency symbol (e.g., $, €, £)",
                        max_length=5,
                    ),
                ),
                (
                    "enable_rtl",
                    models.BooleanField(
                        default=False, help_text="Enable Right-to-Left language support"
                    ),
                ),
                (
                    "enable_frontend",
                    models.BooleanField(
                        default=True, help_text="Enable public frontend"
                    ),
                ),
                (
                    "theme",
                    models.CharField(
                        choices=[
                            ("light", "Light"),
                            ("dark", "Dark"),
                            ("auto", "Auto"),
                        ],
                        default="light",
                        max_length=50,
                    ),
                ),
                (
                    "date_format",
                    models.CharField(
                        choices=[
                            ("DD/MM/YYYY", "DD/MM/YYYY"),
                            ("MM/DD/YYYY", "MM/DD/YYYY"),
                            ("YYYY-MM-DD", "YYYY-MM-DD"),
                        ],
                        default="DD/MM/YYYY",
                        max_length=20,
                    ),
                ),
                (
                    "google_analytics",
                    models.CharField(
                        blank=True,
                        help_text="Google Analytics tracking ID",
                        max_length=255,
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        blank=True,
                        help_text="Default system language",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="general_settings",
                        to="admin_settings.language",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "General Settings",
                "db_table": "admin_general_settings",
            },
        ),
    ]
