# Generated by Django 4.2.13 on 2025-11-28 05:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("admin_settings", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("colleges", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_feedback",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="feedback",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="emailsetting",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="email_settings",
                to="colleges.college",
            ),
        ),
        migrations.AddField(
            model_name="activitylog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="academicyear",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="academic_years",
                to="colleges.college",
            ),
        ),
        migrations.AddIndex(
            model_name="languagelabel",
            index=models.Index(
                fields=["language", "label_key"], name="admin_langu_languag_9bfcc3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="languagelabel",
            index=models.Index(
                fields=["label_key"], name="admin_langu_label_k_86cc7c_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="languagelabel",
            unique_together={("language", "label_key")},
        ),
        migrations.AddIndex(
            model_name="feedback",
            index=models.Index(
                fields=["status", "-created_at"], name="admin_feedb_status_0351b3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="feedback",
            index=models.Index(
                fields=["user", "-created_at"], name="admin_feedb_user_id_c1a16f_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="emailsetting",
            unique_together={("school", "email_protocol", "email_type")},
        ),
        migrations.AddIndex(
            model_name="activitylog",
            index=models.Index(
                fields=["-created_at"], name="admin_activ_created_05e410_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="activitylog",
            index=models.Index(
                fields=["user", "-created_at"], name="admin_activ_user_id_692262_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="activitylog",
            index=models.Index(
                fields=["action_type", "-created_at"],
                name="admin_activ_action__dabee1_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="academicyear",
            unique_together={("school", "year")},
        ),
    ]
