# Generated by Django 4.2.13 on 2026-09-14 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("students", "0001_initial"),
        ("colleges", "0002_initial"),
        ("live_classes", "0001_initial"),
        ("academic", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submissions",
                to="students.student",
            ),
        ),
        migrations.AddField(
            model_name="liveclasstype",
            name="college",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="colleges.college",
            ),
        ),
        migrations.AddField(
            model_name="liveclass",
            name="college",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="colleges.college",
            ),
        ),
        migrations.AddField(
            model_name="liveclass",
            name="live_class_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="classes",
                to="live_classes.liveclasstype",
            ),
        ),
        migrations.AddField(
            model_name="liveclass",
            name="school_class",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="live_classes",
                to="academic.schoolclass",
            ),
        ),
        migrations.AddField(
            model_name="liveclass",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="live_classes",
                to="academic.classsection",
            ),
        ),
        migrations.AddField(
            model_name="liveclass",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="live_classes",
                to="academic.subject",
            ),
        ),
    ]
