# Generated by Django 4.2.13 on 2026-09-14 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("colleges", "0002_initial"),
        ("teachers", "0001_initial"),
        ("live_classes", "0002_initial"),
        ("academic", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="liveclass",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="live_classes",
                to="teachers.teacher",
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="college",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="colleges.college",
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="school_class",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="academic.schoolclass",
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="academic.classsection",
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="academic.subject",
            ),
        ),
    ]
