# Generated by Django 4.2.13 on 2025-11-28 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DashboardActivity",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("student_registration", "Student Registration"),
                            ("teacher_registration", "Teacher Registration"),
                            ("payment_received", "Payment Received"),
                            ("attendance_marked", "Attendance Marked"),
                            ("course_created", "Course Created"),
                            ("exam_scheduled", "Exam Scheduled"),
                            ("leave_approved", "Leave Approved"),
                            ("salary_processed", "Salary Processed"),
                            ("result_published", "Result Published"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "related_object_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("related_object_id", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
