# Generated by Django 4.2.13 on 2025-11-28 05:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dashboardactivity",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="dashboardactivity",
            index=models.Index(
                fields=["-timestamp"], name="dashboard_d_timesta_112cf0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dashboardactivity",
            index=models.Index(
                fields=["activity_type", "-timestamp"],
                name="dashboard_d_activit_e41070_idx",
            ),
        ),
    ]
