# Generated by Django 4.2.13 on 2026-09-14 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("students", "0001_initial"),
        ("colleges", "0002_initial"),
        ("academic", "0001_initial"),
        ("student_management", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentactivity",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activities",
                to="students.student",
            ),
        ),
        migrations.AddField(
            model_name="onlineadmission",
            name="college",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="colleges.college",
            ),
        ),
        migrations.AddField(
            model_name="onlineadmission",
            name="school_class",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="online_admissions",
                to="academic.schoolclass",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="studenttype",
            unique_together={("college", "name")},
        ),
    ]
