# Generated by Django 4.2.13 on 2026-09-14 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("students", "0001_initial"),
        ("promotion", "0001_initial"),
        ("academic", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentpromotion",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="promotions",
                to="students.student",
            ),
        ),
        migrations.AddField(
            model_name="studentpromotion",
            name="to_class",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="promoted_to",
                to="academic.schoolclass",
            ),
        ),
        migrations.AddField(
            model_name="studentpromotion",
            name="to_section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="promoted_to_section",
                to="academic.classsection",
            ),
        ),
    ]
