# Generated by Django 4.2.13 on 2025-11-28 05:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersession",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="usermfa",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mfa",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="securityauditlog",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_audit_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="securityauditlog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audit_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="refreshtoken",
            name="replaced_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="replaced_token",
                to="authentication.refreshtoken",
            ),
        ),
        migrations.AddField(
            model_name="refreshtoken",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="refresh_tokens",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="otpcode",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="otp_codes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="blacklistedtoken",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blacklisted_tokens",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(
                fields=["user", "status", "-last_activity"],
                name="user_sessio_user_id_6a99d2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(
                fields=["device_fingerprint", "-created_at"],
                name="user_sessio_device__9c5c40_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="securityauditlog",
            index=models.Index(
                fields=["user", "event_type", "-created_at"],
                name="security_au_user_id_482647_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="securityauditlog",
            index=models.Index(
                fields=["category", "-created_at"],
                name="security_au_categor_0b0606_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="securityauditlog",
            index=models.Index(
                fields=["ip_address", "-created_at"],
                name="security_au_ip_addr_2d9366_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="securityauditlog",
            index=models.Index(
                fields=["success", "-created_at"], name="security_au_success_11c2d9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="securityauditlog",
            index=models.Index(
                fields=["is_suspicious", "-created_at"],
                name="security_au_is_susp_b1de7e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="securityauditlog",
            index=models.Index(
                fields=["-created_at", "event_type"],
                name="security_au_created_87da79_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="refreshtoken",
            index=models.Index(
                fields=["token", "is_revoked"], name="refresh_tok_token_0bd5a1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="refreshtoken",
            index=models.Index(
                fields=["user", "is_revoked"], name="refresh_tok_user_id_893d6c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="otpcode",
            index=models.Index(
                fields=["user", "code_type", "-created_at"],
                name="otp_codes_user_id_073692_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="otpcode",
            index=models.Index(
                fields=["code", "is_used"], name="otp_codes_code_b3c4d3_idx"
            ),
        ),
    ]
