# Generated by Django 4.2.13 on 2025-11-28 05:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("colleges", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CallLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "call_type",
                    models.CharField(
                        choices=[("Incoming", "Incoming"), ("Outgoing", "Outgoing")],
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=20)),
                ("call_date", models.DateField()),
                (
                    "follow_up",
                    models.BooleanField(default=False, help_text="Mark for follow-up"),
                ),
                (
                    "call_duration",
                    models.IntegerField(
                        help_text="Duration in seconds",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("note", models.TextField(blank=True)),
                ("call_purpose", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "db_table": "call_logs",
                "ordering": ["-call_date"],
            },
        ),
        migrations.CreateModel(
            name="PostalDispatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("to_title", models.CharField(max_length=255)),
                ("reference_number", models.CharField(max_length=100, unique=True)),
                ("address", models.TextField()),
                ("note", models.TextField(blank=True)),
                ("dispatch_date", models.DateField()),
                (
                    "attachment",
                    models.FileField(
                        blank=True, null=True, upload_to="postal/dispatch/"
                    ),
                ),
            ],
            options={
                "db_table": "postal_dispatches",
            },
        ),
        migrations.CreateModel(
            name="PostalReceive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("from_title", models.CharField(max_length=255)),
                ("reference_number", models.CharField(max_length=100, unique=True)),
                ("address", models.TextField()),
                ("note", models.TextField(blank=True)),
                ("receive_date", models.DateField()),
                (
                    "receiver_type",
                    models.CharField(
                        choices=[
                            ("Admin", "Admin"),
                            ("Guardian", "Guardian"),
                            ("Student", "Student"),
                            ("Teacher", "Teacher"),
                            ("Staff", "Staff"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "attachment",
                    models.FileField(
                        blank=True, null=True, upload_to="postal/receive/"
                    ),
                ),
            ],
            options={
                "db_table": "postal_receives",
            },
        ),
        migrations.CreateModel(
            name="VisitorPurpose",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("purpose", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "college",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="colleges.college",
                    ),
                ),
            ],
            options={
                "db_table": "visitor_purposes",
            },
        ),
        migrations.CreateModel(
            name="Visitor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=20)),
                (
                    "visitor_id",
                    models.CharField(
                        blank=True,
                        help_text="National ID, Passport, etc.",
                        max_length=50,
                    ),
                ),
                (
                    "meet_user_type",
                    models.CharField(
                        choices=[
                            ("Staff", "Staff"),
                            ("Student", "Student"),
                            ("Faculty", "Faculty"),
                            ("Principal", "Principal"),
                            ("Other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("number_of_people", models.IntegerField(default=1)),
                ("check_in_date", models.DateField()),
                ("check_in_time", models.TimeField()),
                ("check_out_date", models.DateField(blank=True, null=True)),
                ("check_out_time", models.TimeField(blank=True, null=True)),
                ("note", models.TextField(blank=True)),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="visitors/photos/"
                    ),
                ),
                (
                    "attachment",
                    models.FileField(
                        blank=True, null=True, upload_to="visitors/attachments/"
                    ),
                ),
                (
                    "college",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="colleges.college",
                    ),
                ),
            ],
            options={
                "db_table": "visitor_info",
                "ordering": ["-check_in_date", "-check_in_time"],
            },
        ),
    ]
