# Generated by Django 4.2.13 on 2025-11-28 05:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("front_office", "0001_initial"),
        ("colleges", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="visitor",
            name="meet_staff_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="visitors_met",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="visitor",
            name="purpose",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="visitors",
                to="front_office.visitorpurpose",
            ),
        ),
        migrations.AddField(
            model_name="postalreceive",
            name="college",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="colleges.college",
            ),
        ),
        migrations.AddField(
            model_name="postaldispatch",
            name="college",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="colleges.college",
            ),
        ),
        migrations.AddField(
            model_name="calllog",
            name="college",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="colleges.college",
            ),
        ),
        migrations.CreateModel(
            name="VisitorInfo",
            fields=[],
            options={
                "verbose_name_plural": "Visitor Info",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("front_office.visitor",),
        ),
    ]
