# Generated by Django 4.2.13 on 2026-09-14 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("students", "0001_initial"),
        ("exam_management", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="examattendancerecord",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="students.student"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="examterm",
            unique_together={("college", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="examschedule",
            unique_together={("exam_term", "school_class", "section", "subject")},
        ),
        migrations.AlterUniqueTogether(
            name="examattendancerecord",
            unique_together={("exam_schedule", "student")},
        ),
    ]
