# Generated by Django 4.2.13 on 2026-09-14 23:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("colleges", "0002_initial"),
        ("academic", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CertificateType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("certificate_name", models.CharField(max_length=255)),
                ("school_name", models.CharField(max_length=255)),
                (
                    "certificate_text",
                    models.TextField(
                        help_text="Use tags: [name], [class], [roll], [session], [date], [father_name], [mother_name]"
                    ),
                ),
                ("footer_left_text", models.CharField(blank=True, max_length=255)),
                ("footer_middle_text", models.CharField(blank=True, max_length=255)),
                ("footer_right_text", models.CharField(blank=True, max_length=255)),
                (
                    "background",
                    models.ImageField(
                        blank=True, null=True, upload_to="certificate_backgrounds/"
                    ),
                ),
                (
                    "college",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="colleges.college",
                    ),
                ),
            ],
            options={
                "db_table": "certificate_types",
            },
        ),
        migrations.CreateModel(
            name="CertificateGeneration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "generated_certificate",
                    models.FileField(
                        blank=True, null=True, upload_to="generated_certificates/"
                    ),
                ),
                (
                    "certificate_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="certificates.certificatetype",
                    ),
                ),
                (
                    "college",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="colleges.college",
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="academic.schoolclass",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="academic.classsection",
                    ),
                ),
            ],
            options={
                "db_table": "certificate_generations",
            },
        ),
    ]
