# Generated by Django 4.2.13 on 2026-09-14 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("colleges", "0002_initial"),
        ("academic", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExamInstruction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("title", models.CharField(max_length=255)),
                ("instruction", models.TextField()),
            ],
            options={
                "db_table": "exam_instructions",
            },
        ),
        migrations.CreateModel(
            name="OnlineExam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("exam_title", models.CharField(max_length=255)),
                ("exam_date", models.DateField()),
                ("exam_time", models.TimeField()),
                (
                    "duration_minutes",
                    models.IntegerField(help_text="Duration in minutes"),
                ),
                ("total_mark", models.DecimalField(decimal_places=2, max_digits=6)),
                ("passing_mark", models.DecimalField(decimal_places=2, max_digits=6)),
                ("publish_status", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "online_exams",
            },
        ),
        migrations.CreateModel(
            name="QuestionBank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("Multiple Choice", "Multiple Choice"),
                            ("True/False", "True/False"),
                            ("Short Answer", "Short Answer"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "question_level",
                    models.CharField(
                        choices=[
                            ("Easy", "Easy"),
                            ("Medium", "Medium"),
                            ("Hard", "Hard"),
                        ],
                        max_length=10,
                    ),
                ),
                ("question", models.TextField()),
                ("option_a", models.CharField(blank=True, max_length=500)),
                ("option_b", models.CharField(blank=True, max_length=500)),
                ("option_c", models.CharField(blank=True, max_length=500)),
                ("option_d", models.CharField(blank=True, max_length=500)),
                ("correct_answer", models.CharField(max_length=500)),
                ("mark", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "college",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="colleges.college",
                    ),
                ),
                (
                    "school_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="academic.schoolclass",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="academic.classsection",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="academic.subject",
                    ),
                ),
            ],
            options={
                "db_table": "question_bank",
            },
        ),
        migrations.CreateModel(
            name="OnlineExamResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "answers",
                    models.JSONField(default=dict, help_text="Student answers"),
                ),
                ("obtained_mark", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "status",
                    models.CharField(
                        choices=[("Pass", "Pass"), ("Fail", "Fail")], max_length=10
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "college",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="colleges.college",
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="online_exam.onlineexam",
                    ),
                ),
            ],
            options={
                "db_table": "online_exam_results",
            },
        ),
    ]
