# Generated by Django 4.2.13 on 2026-09-14 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("students", "0001_initial"),
        ("colleges", "0002_initial"),
        ("academic", "0001_initial"),
        ("online_exam", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="onlineexamresult",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="students.student"
            ),
        ),
        migrations.AddField(
            model_name="onlineexam",
            name="college",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="colleges.college",
            ),
        ),
        migrations.AddField(
            model_name="onlineexam",
            name="instruction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="online_exam.examinstruction",
            ),
        ),
        migrations.AddField(
            model_name="onlineexam",
            name="questions",
            field=models.ManyToManyField(
                related_name="exams", to="online_exam.questionbank"
            ),
        ),
        migrations.AddField(
            model_name="onlineexam",
            name="school_class",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="academic.schoolclass"
            ),
        ),
        migrations.AddField(
            model_name="onlineexam",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="academic.classsection"
            ),
        ),
        migrations.AddField(
            model_name="onlineexam",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="academic.subject"
            ),
        ),
        migrations.AddField(
            model_name="examinstruction",
            name="college",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="colleges.college",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="onlineexamresult",
            unique_together={("exam", "student")},
        ),
    ]
