# Generated by Django 4.2.13 on 2025-11-28 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("colleges", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SMSTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("general", "General"),
                            ("admission", "Admission"),
                            ("fee", "Fee"),
                            ("attendance", "Attendance"),
                            ("exam", "Exam"),
                            ("holiday", "Holiday"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Use tags: {name}, {email}, {phone}, {school}, {class}, {section}, {roll}, {subject}"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "college",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="colleges.college",
                    ),
                ),
            ],
            options={
                "db_table": "sms_templates",
            },
        ),
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("general", "General"),
                            ("admission", "Admission"),
                            ("fee", "Fee"),
                            ("attendance", "Attendance"),
                            ("exam", "Exam"),
                            ("holiday", "Holiday"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
                (
                    "content",
                    models.TextField(
                        help_text="Use tags: {name}, {email}, {phone}, {school}, {class}, {section}, {roll}, {subject}"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "college",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="colleges.college",
                    ),
                ),
            ],
            options={
                "db_table": "email_templates",
            },
        ),
    ]
