# Generated by Django 4.2.13 on 2026-09-14 23:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("colleges", "0002_initial"),
        ("exam_management", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExamMark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "written_mark",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "tutorial_mark",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "practical_mark",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "viva_mark",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "total_mark",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "attendance_status",
                    models.CharField(
                        choices=[("Present", "Present"), ("Absent", "Absent")],
                        default="Present",
                        max_length=10,
                    ),
                ),
                ("note", models.TextField(blank=True)),
            ],
            options={
                "db_table": "exam_marks",
            },
        ),
        migrations.CreateModel(
            name="MarkDistribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "written_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "tutorial_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "practical_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "viva_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
            ],
            options={
                "db_table": "mark_distributions",
            },
        ),
        migrations.CreateModel(
            name="MarkEmailLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("receiver_email", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=255)),
                ("body", models.TextField()),
            ],
            options={
                "db_table": "mark_email_logs",
            },
        ),
        migrations.CreateModel(
            name="MarkSMSLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("receiver_phone", models.CharField(max_length=20)),
                ("message", models.TextField()),
                ("gateway", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "mark_sms_logs",
            },
        ),
        migrations.CreateModel(
            name="ResultCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("total_marks", models.DecimalField(decimal_places=2, max_digits=7)),
                ("obtained_marks", models.DecimalField(decimal_places=2, max_digits=7)),
                ("percentage", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "result_status",
                    models.CharField(
                        choices=[("Pass", "Pass"), ("Fail", "Fail")], max_length=10
                    ),
                ),
                ("merit_position", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "result_cards",
            },
        ),
        migrations.CreateModel(
            name="ResultEmailLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("receiver_email", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=255)),
                ("body", models.TextField()),
            ],
            options={
                "db_table": "result_email_logs",
            },
        ),
        migrations.CreateModel(
            name="ResultSMSLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("receiver_phone", models.CharField(max_length=20)),
                ("message", models.TextField()),
                ("gateway", models.CharField(max_length=100)),
                (
                    "college",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="colleges.college",
                    ),
                ),
                (
                    "exam_term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="exam_management.examterm",
                    ),
                ),
                (
                    "sent_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "result_sms_logs",
            },
        ),
    ]
