# Generated by Django 4.2.13 on 2026-09-14 23:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("colleges", "0002_initial"),
        ("exam_management", "0002_initial"),
        ("academic", "0001_initial"),
        ("marks", "0001_initial"),
        ("students", "0001_initial"),
        ("templates", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="resultsmslog",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="students.student"
            ),
        ),
        migrations.AddField(
            model_name="resultsmslog",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="templates.smstemplate",
            ),
        ),
        migrations.AddField(
            model_name="resultemaillog",
            name="college",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="colleges.college",
            ),
        ),
        migrations.AddField(
            model_name="resultemaillog",
            name="exam_term",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="exam_management.examterm",
            ),
        ),
        migrations.AddField(
            model_name="resultemaillog",
            name="sent_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="resultemaillog",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="students.student"
            ),
        ),
        migrations.AddField(
            model_name="resultemaillog",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="templates.emailtemplate",
            ),
        ),
        migrations.AddField(
            model_name="resultcard",
            name="college",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="colleges.college",
            ),
        ),
        migrations.AddField(
            model_name="resultcard",
            name="exam_term",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="exam_management.examterm",
            ),
        ),
        migrations.AddField(
            model_name="resultcard",
            name="overall_grade",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="exam_management.grade",
            ),
        ),
        migrations.AddField(
            model_name="resultcard",
            name="school_class",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="academic.schoolclass"
            ),
        ),
        migrations.AddField(
            model_name="resultcard",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="academic.classsection"
            ),
        ),
        migrations.AddField(
            model_name="resultcard",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="students.student"
            ),
        ),
        migrations.AddField(
            model_name="marksmslog",
            name="college",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="colleges.college",
            ),
        ),
        migrations.AddField(
            model_name="marksmslog",
            name="exam_schedule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="exam_management.examschedule",
            ),
        ),
        migrations.AddField(
            model_name="marksmslog",
            name="sent_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="marksmslog",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="students.student"
            ),
        ),
        migrations.AddField(
            model_name="marksmslog",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="templates.smstemplate",
            ),
        ),
        migrations.AddField(
            model_name="markemaillog",
            name="college",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="colleges.college",
            ),
        ),
        migrations.AddField(
            model_name="markemaillog",
            name="exam_schedule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="exam_management.examschedule",
            ),
        ),
        migrations.AddField(
            model_name="markemaillog",
            name="sent_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="markemaillog",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="students.student"
            ),
        ),
        migrations.AddField(
            model_name="markemaillog",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="templates.emailtemplate",
            ),
        ),
        migrations.AddField(
            model_name="markdistribution",
            name="college",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="colleges.college",
            ),
        ),
        migrations.AddField(
            model_name="markdistribution",
            name="exam_term",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="exam_management.examterm",
            ),
        ),
        migrations.AddField(
            model_name="markdistribution",
            name="school_class",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="academic.schoolclass"
            ),
        ),
        migrations.AddField(
            model_name="markdistribution",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="academic.subject"
            ),
        ),
        migrations.AddField(
            model_name="exammark",
            name="college",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="colleges.college",
            ),
        ),
        migrations.AddField(
            model_name="exammark",
            name="exam_schedule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="marks",
                to="exam_management.examschedule",
            ),
        ),
        migrations.AddField(
            model_name="exammark",
            name="grade",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="exam_management.grade",
            ),
        ),
        migrations.AddField(
            model_name="exammark",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="students.student"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="resultcard",
            unique_together={("exam_term", "student")},
        ),
        migrations.AlterUniqueTogether(
            name="markdistribution",
            unique_together={("exam_term", "school_class", "subject")},
        ),
        migrations.AlterUniqueTogether(
            name="exammark",
            unique_together={("exam_schedule", "student")},
        ),
    ]
