# Generated by Django 4.2.13 on 2026-09-14 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("students", "0001_initial"),
        ("colleges", "0002_initial"),
        ("scholarship", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="scholarshipcandidate",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scholarship_applications",
                to="students.student",
            ),
        ),
        migrations.AddField(
            model_name="scholarship",
            name="candidate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scholarships",
                to="scholarship.scholarshipcandidate",
            ),
        ),
        migrations.AddField(
            model_name="scholarship",
            name="college",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="colleges.college",
            ),
        ),
        migrations.AddField(
            model_name="donor",
            name="college",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="colleges.college",
            ),
        ),
    ]
