# Generated by Django 4.2.13 on 2025-11-28 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="College",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school_url",
                    models.SlugField(
                        blank=True,
                        help_text="School URL (no spaces, capitals, or special chars)",
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=50, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("address", models.TextField(blank=True, null=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("registration_date", models.DateField(blank=True, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("fax", models.CharField(blank=True, max_length=20, null=True)),
                ("footer", models.TextField(blank=True, null=True)),
                (
                    "currency",
                    models.CharField(blank=True, default="USD", max_length=10),
                ),
                (
                    "currency_symbol",
                    models.CharField(blank=True, default="$", max_length=5, null=True),
                ),
                ("enable_frontend", models.BooleanField(default=True)),
                (
                    "exam_final_result",
                    models.CharField(
                        choices=[
                            ("Average of All Exam", "Average of All Exam"),
                            ("Highest Exam", "Highest Exam"),
                            ("Lowest Exam", "Lowest Exam"),
                            ("Percentage", "Percentage"),
                        ],
                        default="Average of All Exam",
                        max_length=100,
                    ),
                ),
                ("theme", models.CharField(blank=True, default="light", max_length=50)),
                ("online_admission", models.BooleanField(default=False)),
                ("enable_rtl", models.BooleanField(default=False)),
                (
                    "zoom_api_key",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "zoom_secret",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "google_map",
                    models.TextField(
                        blank=True, help_text="Google Map embed code", null=True
                    ),
                ),
                ("facebook_url", models.URLField(blank=True, null=True)),
                ("twitter_url", models.URLField(blank=True, null=True)),
                ("linkedin_url", models.URLField(blank=True, null=True)),
                ("youtube_url", models.URLField(blank=True, null=True)),
                ("instagram_url", models.URLField(blank=True, null=True)),
                ("pinterest_url", models.URLField(blank=True, null=True)),
                (
                    "frontend_logo",
                    models.ImageField(
                        blank=True,
                        help_text="Max-W: 150px, Max-H: 90px",
                        null=True,
                        upload_to="school_logos/frontend/",
                    ),
                ),
                (
                    "admin_logo",
                    models.ImageField(
                        blank=True,
                        help_text="Max-W: 100px, Max-H: 110px",
                        null=True,
                        upload_to="school_logos/admin/",
                    ),
                ),
                ("website", models.URLField(blank=True, null=True)),
                ("established_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "verbose_name": "College",
                "verbose_name_plural": "Colleges",
                "db_table": "colleges",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(blank=True, max_length=50, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "college",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="departments",
                        to="colleges.college",
                    ),
                ),
            ],
            options={
                "verbose_name": "Department",
                "verbose_name_plural": "Departments",
                "db_table": "departments",
                "ordering": ["college", "name"],
            },
        ),
    ]
