# Generated by Django 4.2.13 on 2025-11-28 05:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("admin_settings", "0002_initial"),
        ("colleges", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="head",
            field=models.ForeignKey(
                blank=True,
                db_column="head_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="department_head_of",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="college",
            name="language",
            field=models.ForeignKey(
                blank=True,
                help_text="College-specific language setting",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="colleges",
                to="admin_settings.language",
            ),
        ),
        migrations.AddField(
            model_name="college",
            name="principal",
            field=models.ForeignKey(
                blank=True,
                db_column="principal_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="college_principal_of",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="department",
            index=models.Index(
                fields=["college"], name="departments_college_30730c_idx"
            ),
        ),
    ]
